### ISSUE TITLE
Incorrect error shown in CIF (from STAR writer)

### ISSUE THREAD

**Issue by rozyczko** [easyScience/easyCore#88]
Run the PbSO4 example.
Refine the Uiso for O1.
The result is `0.0232 +- 0.0003`, which is correctly shown in the Parameters table on the Analysis page.
But the CIF editor on the Sample page shows it incorrectly as `0.0232(34814)`.
It should be either `0.0232(3)` or `0.0232XXXX(34814)`.

**Comment by wardsimon** [comment]
This should be fixed on v0.2.1 and greater.
